version: '3.8'
services:
  snmp-mibserver:
    image: ${MIBSERVER_IMAGE}:${MIBSERVER_TAG:-latest}
    container_name: snmp-mibserver
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=${NGINX_ENTRYPOINT_QUIET_LOGS:-1}
    volumes:
      - snmp-mibserver-tmp:/tmp/
    depends_on:
      - coredns
    networks:
      - my_network
    dns:
      - ${COREDNS_ADDRESS}

  redis:
    image: ${REDIS_IMAGE}:${REDIS_TAG:-latest}
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - coredns
    networks:
      - my_network
    dns:
      - ${COREDNS_ADDRESS}
  mongo:
    image: ${MONGO_IMAGE}:${MONGO_TAG:-latest}
    container_name: mongo
    restart: always
    depends_on:
      - coredns
    networks:
      - my_network
    dns:
      - ${COREDNS_ADDRESS}
volumes:
  snmp-mibserver-tmp: null
