services:
  traps:
    command:
    - trap
    container_name: sc4snmp-traps
    depends_on:
    - redis
    - mongo
    - coredns
    dns:
    - ${COREDNS_ADDRESS}
    environment:
    - CONFIG_PATH=/app/config/config.yaml
    - REDIS_URL=redis://redis:6379/1
    - CELERY_BROKER_URL=redis://redis:6379/0
    - MONGO_URI=mongodb://mongo:27017/
    - MIB_SOURCES=http://snmp-mibserver:8000/asn1/@mib@
    - MIB_INDEX=http://snmp-mibserver:8000/index.csv
    - MIB_STANDARD=http://snmp-mibserver:8000/standard.txt
    - LOG_LEVEL=${SCHEDULER_LOG_LEVEL:-INFO}
    - INVENTORY_REFRESH_RATE=${INVENTORY_REFRESH_RATE:-600}
    - SPLUNK_HEC_HOST=${SPLUNK_HEC_HOST}
    - SPLUNK_HEC_SCHEME=${SPLUNK_HEC_PROTOCOL:-https}
    - SPLUNK_HEC_PORT=${SPLUNK_HEC_PORT}
    - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
    - SPLUNK_HEC_INSECURESSL=${SPLUNK_HEC_INSECURESSL:-false}
    - SPLUNK_HEC_PATH=${SPLUNK_HEC_PATH:-/services/collector}
    - SNMP_V3_SECURITY_ENGINE_ID=${SNMP_V3_SECURITY_ENGINE_ID:-80003a8c04}
    image: ${SC4SNMP_IMAGE}:${SC4SNMP_TAG:-latest}
    networks:
      - my_network
    ports:
    - mode: host
      protocol: udp
      published: ${TRAPS_PORT}
      target: 2162
    restart: on-failure
    secrets: []
    volumes:
    - ${TRAPS_CONFIG_FILE_ABSOLUTE_PATH}:/app/config/config.yaml
    - traps-pysnmp-cache-volume:/.pysnmp/
    - traps-tmp:/tmp/
version: '3.8'
volumes:
  traps-pysnmp-cache-volume: null
  traps-tmp: null
