version: '3.8'
networks:
  sc4snmp_network:
    name: sc4snmp_network
    enable_ipv6: ${IPv6_ENABLED:-false}
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
        - subnet: fd02::/64
          gateway: fd02::1