apiVersion: v1
kind: Service
metadata:
  name: otel-service
spec:
  type: ClusterIP
  ports:
    - port: 8881
      name: logs
    - port: 8882
      name: metrics
  selector:
    app: sc4-snmp-otel
---
