{{- if and .Values.sim.secret.create .Values.sim.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-connect-for-snmp.name" . }}-sim
type: Opaque
data:
  signalfxToken: {{ .Values.sim.signalfxToken | b64enc | quote }}
  signalfxRealm: {{ .Values.sim.signalfxRealm | b64enc | quote }}
{{- end }}
