{{- if .Values.sim.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-connect-for-snmp.sim.serviceAccountName" . }}
  labels:
    {{- include "splunk-connect-for-snmp.sim.labels" . | nindent 4 }}
  {{- with .Values.sim.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
