version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "ci(actions): "
    directory: "/.github/workflows"
    rebase-strategy: "disabled"
    target-branch: "develop"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: ""
    target-branch: "develop"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(pip): "
      include: "scope"
