apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc4snmp-traps
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: sc4snmp-traps
spec:
  replicas: {{ .Values.traps.replicas }}
  selector:
    matchLabels:
      app: sc4snmp-traps
  template:
    metadata:
      labels:
        app: sc4snmp-traps
    spec:
      securityContext:
          runAsNonRoot: true      
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 2000    
      containers:
        - name: traps
          image: {{ .Values.traps.image | default "ghcr.io/splunk/splunk-connect-for-snmp-traps/container" }}:{{ .Values.traps.tag | default "1" }}
          imagePullPolicy: {{ .Values.traps.pullPolicy | default "IfNotPresent" }}
          args:
            [
              {{ printf "\"--loglevel=%s\"" ( .Values.traps.logLevel | default "WARN" ) }},
              "--config=/work/config/config.yaml",
              "--index={{ .Values.scheduler.index.event }}",
              "--ipv6=",
            ]
          securityContext:
            allowPrivilegeEscalation: false          
          ports:
            - containerPort: 2162
          env:
            - name: MIBS_SERVER_URL
              value: {{ printf "http://sc4snmp-mib-server-service:%s" "5000" | quote }}
            - name: OTEL_SERVER_URL
              value: {{ printf "http://otel-service:%s" "8881" | quote }}
            - name: SPLUNK_HEC_URL
              valueFrom:
                secretKeyRef:
                  name: remote-splunk
                  key: splunkHecUrl
            - name: SPLUNK_HEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: remote-splunk
                  key: splunkHecToken
            - name: SPLUNK_HEC_TLS_SKIP_VERIFY
              valueFrom:
                secretKeyRef:
                  name: remote-splunk
                  key: splunkHecTlsSkipVerify
          volumeMounts:
            - name: config
              mountPath: "/work/config"
              readOnly: true
          resources:
            {{- if .Values.traps.resources }}
{{ .Values.traps.resources | toYaml | trim | indent 12 }}
            {{ else }}
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
            {{ end }}
      volumes:
        - name: config
          configMap:
            name: sc4snmp-trap
            items:
              - key: "config.yaml"
                path: "config.yaml"
