scheduler:
  logLevel: "WARN"
  index:
    event: em_logs
    metrics: em_metrics
    meta: em_meta
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  inventory:
    content: |-
      #10.0.0.1,2c,public,basev1,300
splunk:
  protocol: https
  host: i-0e9ea145205eab24d.ec2.splunkit.io
  insecureSSL: "true"
  token: 00000000-0000-0000-0000-000000000000
  port: "8088"
  clusterName: foo
traps:
  loadBalancerIP: 10.202.16.24
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      memory: 128Mi
mode: "both"
mib:
  service_host: sc4snmp-mib-server-service
  service_port: "5000"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
otel:
  service_host: otel-service
  service_metrics_port: "8882"
  service_logs_port: "8881"
worker:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
#mongodb:
#  fullnameOverride: "sc4snmp-mongodb"
#  metrics:
#    enabled: true
#    image:
#      registry: docker.io
#      repository: bitnami/mongodb-exporter
#      tag: 0.10.0-debian-10-r41
#      pullPolicy: IfNotPresent
#  persistence:
#    enabled: true
#    accessModes:
#      - ReadWriteOnce
#    size: 8Gi
#    mountPath: /bitnami/mongodb
#  auth:
#      enabled: false

