{{- if and .Values.scheduler.networkPolicy ( eq (include "splunk-connect-for-snmp.polling.enable" .) "true" ) -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "splunk-connect-for-snmp.scheduler.fullname" . }}
  labels: 
    {{- include "splunk-connect-for-snmp.scheduler.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
    {{- include "splunk-connect-for-snmp.scheduler.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}