{{- if eq (include "splunk-connect-for-snmp.polling.enable" .) "true" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "splunk-connect-for-snmp.scheduler.fullname" . }}
  labels: 
    {{- include "splunk-connect-for-snmp.scheduler.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: 
    {{- include "splunk-connect-for-snmp.scheduler.selectorLabels" . | nindent 8 }}
{{- end }}
