apiVersion: v1
kind: ConfigMap
metadata:
  name: sc4snmp-inventory
  namespace: {{ .Release.Namespace | quote }}
data:
  inventory.csv: |
    host,version,community,profile,freqinseconds
    #10.0.0.1,2c,public,basev1,300
