{{- if and ( eq (include "splunk-connect-for-snmp.polling.enable" .) "true" ) (eq ( toString .Values.worker.poller.autoscaling.enabled) "true") ( eq ( toString .Values.useDeprecatedAPI ) "true" ) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "splunk-connect-for-snmp.worker.fullname" . }}-poller
  labels:
    {{- include "splunk-connect-for-snmp.worker.poller.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "splunk-connect-for-snmp.worker.fullname" . }}-poller
  minReplicas: {{ .Values.worker.poller.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.worker.poller.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.worker.poller.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.worker.poller.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
