{{- if .Values.worker.poller.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "splunk-connect-for-snmp.worker.fullname" . }}-poller
  labels:
    {{- include "splunk-connect-for-snmp.worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "splunk-connect-for-snmp.worker.fullname" . }}-poller
  minReplicas: {{ .Values.worker.poller.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.worker.poller.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.worker.poller.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        type: Utilization
        averageUtilization: {{ .Values.worker.poller.autoscaling.targetCPUUtilizationPercentage | default 80 }}
    {{- end }}
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
{{- end }}
