apiVersion: v1
kind: Service
metadata:
  name: sc4snmp-mib-server-service
  namespace: sc4snmp
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: sc4snmp-mib-server

