apiVersion: v1
kind: Service
metadata:
  name: otel-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 8881
      name: logs
    - port: 8882
      name: metrics
  selector:
    app: sc4snmp-otel
