{{ if .Values.UI.enable }}
apiVersion: v1
kind: Service
metadata:
  name: ui-backend-entrypoint
spec:
  selector:
    app: ui-backend
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: {{ .Values.UI.backEnd.NodePort }}
{{- end }}