[pytest]
asyncio_mode = strict  
asyncio_debug = true
markers =
    part1: marks tests as belonging to part 1 of a test suite
    part2: marks tests as belonging to part 2 of a test suite
    part3: marks tests as belonging to part 3 of a test suite
    part4: marks tests as belonging to part 4 of a test suite
    part5: marks tests as belonging to part 5 of a test suite
    part6: marks tests as belonging to part 6 of a test suite

addopts = -s -rfps --durations=10 --disable-pytest-warnings --continue-on-collection-errors

# Keep these to ensure pytest's internal logging system is also active
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

