apiVersion: v1
kind: Service
metadata:
  name: splunk-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.151
  ports:
    - port: 8000
      name: web
    - port: 8080
      name: hec
    - port: 8089
      name: rest
  selector:
    app: splunk

