apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
        - name: snmp-sim
          image: splunk/splunk:8.1.3
          ports:
            - containerPort: 8000
            - containerPort: 8080
            - containerPort: 8089
          env:
            - name: SPLUNK_START_ARGS
              value: --accept-license
            - name: SPLUNK_PASSWORD
              value: changedpassword
