apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splunk-connect-for-snmp.worker.fullname" . }}-trap
  labels:
    {{- include "splunk-connect-for-snmp.worker.trap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.worker.trap.autoscaling.enabled }}
  replicas: {{ .Values.worker.trap.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "splunk-connect-for-snmp.worker.trap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "splunk-connect-for-snmp.worker.trap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "splunk-connect-for-snmp.worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker-trap
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            [
              "celery", "worker-trap",
            ]
          {{- include "environmental-variables" . | nindent 10 }}
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
            - name: pysnmp-cache-volume
              mountPath: "/.pysnmp/"
              readOnly: false
            - name: tmp
              mountPath: "/tmp/"
              readOnly: false
            {{- if (.Values.poller).usernameSecrets }}
            - name: snmpv3-secrets
              mountPath: "/app/secrets/snmpv3"
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.worker.trap.resources | nindent 12 }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.worker.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                    {{- include "splunk-connect-for-snmp.worker.trap.selectorLabels" . | nindent 22 }}
      {{- else if eq .Values.worker.podAntiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "splunk-connect-for-snmp.worker.trap.selectorLabels" . | nindent 22 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: {{ include "splunk-connect-for-snmp.name" . }}-config
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "config.yaml"
                path: "config.yaml"
        {{- if (.Values.poller).usernameSecrets }}
        - name: snmpv3-secrets
          projected:
            sources:
            {{- range .Values.poller.usernameSecrets }}
            {{- $secret := (lookup "v1" "Secret" $.Release.Namespace . ) -}}
            {{- if $secret }}
            - secret:
                name: {{ . }}
                items:
                  {{ if $secret.data.userName -}}
                  - key: userName
                    path: {{ . }}/userName
                  {{- end }}
                  {{ if $secret.data.authKey -}}
                  - key: authKey
                    path: {{ . }}/authKey
                  {{- end }}
                  {{ if $secret.data.privKey -}}
                  - key: privKey
                    path: {{ . }}/privKey
                  {{- end }}
                  {{ if $secret.data.authProtocol -}}
                  - key: authProtocol
                    path: {{ . }}/authProtocol
                  {{- end }}
                  {{ if $secret.data.privProtocol -}}
                  - key: privProtocol
                    path: {{ . }}/privProtocol
                  {{- end }}
                  {{ if $secret.data.contextEngineId -}}
                  - key: contextEngineId
                    path: {{ . }}/contextEngineId
                  {{- end }}
                  {{ if $secret.data.contextName -}}
                  - key: contextName
                    path: {{ . }}/contextName
                  {{- end }}
            {{- end }}
            {{- end }}
        {{- end }}
        - name: pysnmp-cache-volume
          emptyDir: {}
        - name: tmp
          emptyDir: {}