splunk:
  enabled: true
  protocol: https
  host: i-0d903f60788be4c68.ec2.splunkit.io
  token: 00000000-0000-0000-0000-000000000000
  insecureSSL: "false"
  port: "8088"
# in the worker section you can adjust scaling parameters
# full description is here:
# https://splunk.github.io/splunk-connect-for-snmp/main/configuration/worker-configuration
worker:
  poller:
    replicaCount: 5
  sender:
    replicaCount: 3
scheduler:
  profiles: |
    small_walk:
      condition:
        type: walk
      varBinds:
        - ["TCP-MIB"]
        - ["IF-MIB"]
        - ["IP-MIB"]
    IF_profile:
      frequency: 600
      varBinds:
        - [ 'IF-MIB', 'ifDescr' ]
        - [ 'IF-MIB', 'ifAdminStatus' ]
        - [ 'IF-MIB', 'ifName' ]
        - [ 'IF-MIB', 'ifAlias' ]
        - [ 'IF-MIB', 'ifInDiscards' ]
        - [ 'IF-MIB', 'ifInErrors' ]
        - [ 'IF-MIB', 'ifInNUcastPkts' ]
        - [ 'IF-MIB', 'ifInOctets' ]
        - [ 'IF-MIB', 'ifInUcastPkts' ]
        - [ 'IF-MIB', 'ifInUnknownProtos' ]
        - [ 'IF-MIB', 'ifOutDiscards' ]
        - [ 'IF-MIB', 'ifOutErrors' ]
        - [ 'IF-MIB', 'ifOutNUcastPkts' ]
        - [ 'IF-MIB', 'ifOutOctets' ]
        - [ 'IF-MIB', 'ifOutQLen' ]
        - [ 'IF-MIB', 'ifOutUcastPkts' ]
    ICMP_profile:
      frequency: 500
      varBinds:
        - ["IP-MIB", "icmp"]
poller:
  inventory: |
    address,port,version,community,secret,security_engine,walk_interval,profiles,smart_profiles,delete
    54.82.4.248,,2c,public,,,4000,small_walk;IF_profile;ICMP_profile,,
    54.82.4.249,,2c,public,,,1800,small_walk;IF_profile,,