{{- if and .Values.mongodb.auth.enabled (eq .Values.mongodb.mode "replication") (not .Values.mongodb.auth.existingReplicaKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-replicakey
  labels:
    {{- include "splunk-connect-for-snmp.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Release.Name }}-mongodb
type: Opaque
data:
  replica-key: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}