{{- if and .Values.mongodb.auth.enabled (eq .Values.mongodb.mode "replicaset") (not .Values.mongodb.auth.existingReplicaKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-replicakey
  labels:
    app: {{ .Release.Name }}-mongodb
type: Opaque
data:
  replica-key: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}