{{- if and ( not .Values.mongodb.auth.existingSecret ) .Values.mongodb.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-mongodb
type: Opaque
data:
  root-user: {{ .Values.mongodb.auth.rootUser | default "root" | b64enc | quote }}
  root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
{{- end }}