apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-fcv-upgrade-to-7
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: mongo-fcv-upgrade
          image: docker.io/bitnami/mongodb
          command:
            - /bin/bash
            - -c
            - |
              echo "Checking current mongo FCV"
              FCV=$(mongosh --host {{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local --quiet --eval 'db.adminCommand({ getParameter: 1, featureCompatibilityVersion: 1 }).featureCompatibilityVersion.version')
              echo "Current Mongo Feature Compatibility Version: $FCV"
              
              if [[ "$FCV" < "7.0" ]]; then
                echo "FCV < 7.0, setting to 7.0"
                mongosh --host {{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local --eval 'db.adminCommand({ setFeatureCompatibilityVersion: "7.0" })'
              else
                echo "FCV >= 7.0, nothing to be changed"
              fi
      restartPolicy: Never
