apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-fcv-check
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: mongo-fcv-check
          image: docker.io/bitnami/mongodb
          command:
            - /bin/bash
            - -c
            - |
              echo "Checking current mongo feature compability version"
              MONGO_FT_COMPABILITY_VERSION=$(mongosh --host {{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local --quiet --eval 'db.adminCommand({ getParameter: 1, featureCompatibilityVersion: 1 }).featureCompatibilityVersion.version')              echo "Current FCV: $FCV"
              echo "Current Mongo Feature Compability Version: $MONGO_FT_COMPABILITY_VERSION"
              
              if [[ "$MONGO_FT_COMPABILITY_VERSION" < "6.0" ]]; then
                echo "MONGO_FT_COMPABILITY_VERSION < 6.0, setting na 6.0"
                mongosh --host {{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local --eval 'db.adminCommand({ setFeatureCompatibilityVersion: "6.0" })'
              else
                echo "MONGO_FT_COMPABILITY_VERSION >= 6.0, nothing to be changed"
              fi
      restartPolicy: Never
