apiVersion: v1
kind: Service
metadata:
  name: sc4snmp-scheduler-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 8765
      targetPort: 8765
  selector:
    app: sc4snmp-scheduler

