apiVersion: batch/v1
kind: Job
metadata:
  name: snmp-autodiscovery-loader
spec:
  template:
    spec:
      containers:
        - name: snmp-autodiscovery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Never
          args:
              ["autodiscovery"]
      restartPolicy: OnFailure
