apiVersion: batch/v1
kind: Job
metadata:
  name:
spec:
  template:
    spec:
      containers:
        - name: snmp-autodiscovery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Never
          args:
              ["autodiscovery"]
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true

      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: snmp-config
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "config.yaml"
                path: "config.yaml"
      restartPolicy: OnFailure
