; [pytest]
; log_level = INFO
; addopts = -rfps --durations=10 --disable-pytest-warnings --continue-on-collection-errors
; log_cli = true
; log_cli_level = INFO
; log_cli_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s

; ;log_level = DEBUG


[pytest]
# The -s flag (shortcut for --capture=no) allows logs sent to stdout to appear in the CLI
addopts = -s -rfps --durations=10 --disable-pytest-warnings --continue-on-collection-errors

# Keep these to ensure pytest's internal logging system is also active
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S