apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc4snmp-mib-server
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.mib.replicas }}
  selector:
    matchLabels:
      app: sc4snmp-mib-server
  template:
    metadata:
      labels:
        app: sc4snmp-mib-server
    spec:
      containers:
        - name: sc4snmp-mib-server
          image: {{ .Values.mib.image | default "ghcr.io/splunk/splunk-connect-for-snmp-mib-server/container" }}:{{ .Values.mib.tag | default "1" }}
          imagePullPolicy: {{ .Values.mib.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_SERVICE_SERVICE_HOST
              value: sc4snmp-mongodb-headless
            - name: MONGO_SERVICE_SERVICE_PORT
              value: "27017"
            - name: MIB_SERVER_SERVICE_SERVICE_HOST
              value: sc4snmp-mib-server-service
            - name: MIB_SERVER_SERVICE_SERVICE_PORT
              value: {{ ( .Values.mib.service_port | default "5000" ) | quote }}
            - name: MIBS_FILES_URL
              value: "http://$(MIB_SERVER_SERVICE_SERVICE_HOST):$(MIB_SERVER_SERVICE_SERVICE_PORT)/files/asn1/@mib@"
          resources:
          {{- if .Values.mib.resources }}
{{ .Values.mib.resources | toYaml | trim | indent 12 }}
            {{ else }}
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
            {{ end }}

