{{- if .Values.otel.networkPolicy -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "splunk-connect-for-snmp.otel.fullname" . }}
  labels: 
    {{- include "splunk-connect-for-snmp.otel.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
    {{- include "splunk-connect-for-snmp.otel.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
