{{- if .Values.otel.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sc4snmp-otel
  namespace: {{ .Release.Namespace | quote }}
data:
  otel-collector-config.yaml: |
    receivers:
      splunk_hec/metrics:
        endpoint: 0.0.0.0:8882
      splunk_hec/logs:
        endpoint: 0.0.0.0:8883
    exporters:
      signalfx:
        access_token: $signalfxToken
        realm: $signalfxRealm
    service:
      pipelines:
        metrics:
          receivers: [splunk_hec/metrics]
          exporters: [signalfx]
        logs:
          receivers: [splunk_hec/logs]
          exporters: [signalfx]
{{- end }}