{{- if .Values.otel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-connect-for-snmp.otel.fullname" . }}
  labels:
    {{- include "splunk-connect-for-snmp.otel.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8882
      name: metrics
  selector:
    {{- include "splunk-connect-for-snmp.otel.selectorLabels" . | nindent 4 }}
{{- end }}
