apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi