BaseUpTime:
  frequency: 300
  condition:
    type: "mandatory"
    # field: "SNMPv2-MIB.sysDescr"
    # patterns:
    #   - "^.*"
    #"SNMPv2-MIB.sysObjectID"
  varBinds:
    - ["SNMPv2-MIB", "sysUpTime",0]
BaseDeviceData:
  frequency: 1200
  condition:
    type: "mandatory"
  varBinds:
    # Syntax: [ "MIB-Files", "MIB object name" "MIB index number"]
    - ["SNMPv2-MIB", "sysDescr",0]
    - ["SNMPv2-MIB", "sysName",0]
    - ["SNMPv2-MIB", "sysObjectID",0]
    - ["SNMPv2-MIB", "sysContact",0]
    - ["SNMPv2-MIB", "sysLocation",0]
EnrichIF:
  frequency: 600
  condition:
    type: "base"
  varBinds:
    - ["IF-MIB", "ifDescr"]
    - ["IF-MIB", "ifAdminStatus"]
    - ["IF-MIB", "ifName"]
    - ["IF-MIB", "ifAlias"]
BaseIF:
  frequency: 300
  condition:
    type: "base"
  varBinds:
    # Syntax: [ "MIB-Files", "MIB object name" "MIB index number"]
    - ["IF-MIB", "ifInDiscards"]
    - ["IF-MIB", "ifInErrors"]
    - ["IF-MIB", "ifInNUcastPkts"]
    - ["IF-MIB", "ifInOctets"]
    - ["IF-MIB", "ifInUcastPkts"]
    - ["IF-MIB", "ifInUnknownProtos"]
    - ["IF-MIB", "ifOutDiscards"]
    - ["IF-MIB", "ifOutErrors"]
    - ["IF-MIB", "ifOutNUcastPkts"]
    - ["IF-MIB", "ifOutOctets"]
    - ["IF-MIB", "ifOutQLen"]
    - ["IF-MIB", "ifOutUcastPkts"]
