name: create-charts-zip
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - "main"
      - "develop"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        python-version:
          - 3.10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Zip charts directory and upload it
        run: |
          zip -r charts.zip charts 
          VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: charts.zip
        env:
          ARTIFACT_NAME: charts
