name: create-compose-files
on:
  push:
    branches:
      - fix/docker-compose

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        python-version:
          - 3.9
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Zip docker_compose directory
        run: zip -r docker_compose.zip docker_compose
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: docker_compose.zip
        env:
          ARTIFACT_NAME: docker_compose
