name: Update Semver
on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"
jobs:
  update-semver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-update-semver@v1
