{{- if eq .Values.redis.architecture "standalone" }}
{{- if .Values.redis.storage.enabled }}
{{- $bitnamiPVC := printf "data-%s-redis-master-0" .Release.Name }}
{{- $existingPVC := lookup "v1" "PersistentVolumeClaim" .Release.Namespace $bitnamiPVC }}
{{- $statefulSetPVC := printf "redis-data-%s-redis-master-0" .Release.Name }}
{{- $newPVCExists := lookup "v1" "PersistentVolumeClaim" .Release.Namespace $statefulSetPVC }}
{{- if and $existingPVC (not $newPVCExists) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $statefulSetPVC }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-redis
spec:
  accessModes: {{ toYaml .Values.redis.storage.accessModes | nindent 4 }}
  {{- if .Values.redis.storage.storageClassName }}
  storageClassName: {{ .Values.redis.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
{{- end }}
{{- end }}
{{- end }}