{{- if and .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.redis.auth.password | b64enc }}
{{- end }}